version: '3'
services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST=db
      ports:
        - "5432:5432"
    api:
      environment:
        POSTGRES_DB: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_HOST: "db"
        POSTGRES_PORT: 5432
        SECRET_KEY: 'c-^#em%z6o#)$$j*tj2zb8$$%q9&%yyzae_v!*u=afe(war=!q!!'
      build: .
      command: python manage.py runserver 0.0.0.0:8003
      volumes:
        - .:/code
      ports:
        - "8003:8003"
      depends_on:
        - db