version: '3'
services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST=db
      ports:
        - "5432:5432"
    api:
      build: .
      command:  bash -c " python manage.py flush --no-input
        && python manage.py loaddata initial_data.json
        && python manage.py runserver 0.0.0.0:8003"
      volumes:
        - .:/code
      ports:
        - "8003:8003"
      depends_on:
        - db