# Generated by Django 3.0.8 on 2020-07-31 13:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=255), size=None)),
                ('published_date', models.TextField(max_length=10)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=255), size=None)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('ratings_count', models.IntegerField(blank=True)),
                ('thumbnail', models.TextField(max_length=1024)),
            ],
        ),
    ]
