# Generated by Django 3.0.8 on 2020-08-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.TextField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
