# Generated by Django 3.0.8 on 2020-08-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200801_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ratings_count',
            new_name='rating_count',
        ),
    ]
