# Generated by Django 3.0.8 on 2020-08-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200801_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating_count',
            new_name='ratings_count',
        ),
    ]
