# Generated by Django 3.0.8 on 2020-08-01 11:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200801_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=255), blank=True, size=None),
        ),
    ]
